# docker-compose.yml

version: "3.9"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    hostname: postgres
    networks:
      - dbnet

  discord-bot:
    image: fpluis/flipance-discord-bot
    build:
      context: .
    environment:
      DB_HOSTNAME: "postgres"
    # It's crucial that the postgres image starts first to prepare the DB
    depends_on:
      - postgres
    networks:
      - dbnet
    restart: on-failure

networks:
  dbnet:
    name: flipance-database-network
