name: Build Docker Image
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add default user for postgresql docker container
        run: echo POSTGRES_USER=postgres >> .env
      - name: Add default password for postgresql docker container
        run: echo POSTGRES_PASSWORD=1234 >> .env
      - name: Build the docker-compose stack
        run: docker-compose build
      - name: Push the image to the registry
        run: docker-compose push
